<a href="https://colab.research.google.com/github/muriukiMartin/MLTAskTwo/blob/master/MLTaskTwo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

You are provided with the Housing Pricing dataset.
 
 Prepare a dataset description file
 Prepare the dataset for training
 Fill in Missing Values
 Encode the dataset
 Standardize the dataset
 Perfom feature extraction using PCA
 Perform feature selection using L1
 Train a regression model using PCA with 2 components



In [ ]:
#necessary imports
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LassoCV
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, PowerTransformer
from sklearn.model_selection import train_test_split
from sklearn import linear_model,metrics

In [ ]:
data = pd.read_csv('/content/modified_data.csv')

In [ ]:
data.head() #first n rows

Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0   1          60       RL         65.0     8450   Pave      Reg         Lvl   
1   2          20       RL         80.0     9600   Pave      Reg         Lvl   
2   3          60       RL         68.0    11250   Pave      IR1         Lvl   
3   4          70       RL         60.0     9550   Pave      IR1         Lvl   
4   5          60       RL         84.0    14260   Pave      IR1         Lvl   

  Utilities LotConfig  ... EnclosedPorch 3SsnPorch ScreenPorch PoolArea  \
0    AllPub    Inside  ...             0         0           0        0   
1    AllPub       FR2  ...             0         0           0        0   
2    AllPub    Inside  ...             0         0           0        0   
3    AllPub    Corner  ...           272         0           0        0   
4    AllPub       FR2  ...             0         0           0        0   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0       0      2    2008        WD         Normal     208500  
1       0      5    2007        WD         Normal     181500  
2       0      9    2008        WD         Normal     223500  
3       0      2    2006        WD        Abnorml     140000  
4       0     12    2008        WD         Normal     250000  

[5 rows x 77 columns]

#Fill in missing values


In [ ]:
#search for missing values
data.drop('Id',axis=1,inplace=True) 
#dropping column

In [ ]:
data.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0          60       RL         65.0     8450   Pave      Reg         Lvl   
1          20       RL         80.0     9600   Pave      Reg         Lvl   
2          60       RL         68.0    11250   Pave      IR1         Lvl   
3          70       RL         60.0     9550   Pave      IR1         Lvl   
4          60       RL         84.0    14260   Pave      IR1         Lvl   

  Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0    AllPub    Inside       Gtl  ...             0         0           0   
1    AllPub       FR2       Gtl  ...             0         0           0   
2    AllPub    Inside       Gtl  ...             0         0           0   
3    AllPub    Corner       Gtl  ...           272         0           0   
4    AllPub       FR2       Gtl  ...             0         0           0   

  PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0        0       0       2    2008        WD         Normal    208500  
1        0       0       5    2007        WD         Normal    181500  
2        0       0       9    2008        WD         Normal    223500  
3        0       0       2    2006        WD        Abnorml    140000  
4        0       0      12    2008        WD         Normal    250000  

[5 rows x 76 columns]

In [ ]:
data.shape

(1460, 76)

In [ ]:
#detect missing values
data.isna().any()

MSSubClass       False
MSZoning         False
LotFrontage       True
LotArea          False
Street           False
                 ...  
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice        False
Length: 76, dtype: bool

In [ ]:
#get all features
features = list(data.columns)
features

['MSSubClass',
 'MSZoning',
 'LotFrontage',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'MasVnrArea',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinSF1',
 'BsmtFinType2',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'KitchenQual',
 'TotRmsAbvGrd',
 'Functional',
 'Fireplaces',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageCars',
 'GarageArea',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch

In [ ]:
#features with missing values
missing_feature_values = list(data.columns[data.isna().any()])
missing_feature_values

['LotFrontage',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond']

In [ ]:
#get missing values for each feature
for feature in missing_feature_values:
  print(feature,' ',(data[feature].isna().sum())/len(data)*100)

LotFrontage   17.73972602739726
MasVnrType   0.547945205479452
MasVnrArea   0.547945205479452
BsmtQual   2.5342465753424657
BsmtCond   2.5342465753424657
BsmtExposure   2.6027397260273974
BsmtFinType1   2.5342465753424657
BsmtFinType2   2.6027397260273974
Electrical   0.0684931506849315
FireplaceQu   47.26027397260274
GarageType   5.5479452054794525
GarageYrBlt   5.5479452054794525
GarageFinish   5.5479452054794525
GarageQual   5.5479452054794525
GarageCond   5.5479452054794525


In [ ]:
#Return object with labels on given axis omitted where alternately any or all of the data are missing
data.dropna(axis=1,thresh=0.5*(len(data)),inplace=True)

##Fill in missing values

In [ ]:
mean_fill=['LotFrontage','MasVnrArea']
#bfill: use next valid observation to fill gap
bfill=['FireplaceQu'] 
# ffill: propagate last valid observation forward to next valid backfill
ffill=list(set(missing_feature_values)-set(mean_fill)-set(bfill))

In [ ]:
ffill

['GarageType',
 'GarageYrBlt',
 'BsmtFinType2',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'GarageQual',
 'GarageFinish',
 'Electrical',
 'GarageCond',
 'MasVnrType']

In [ ]:
# fillna() method replaces the NULL values with a specified value
for feature in mean_fill:
  data[feature].fillna(data[feature].mean(),inplace=True)
for feature in ffill:
  data[feature].fillna(method='ffill',inplace=True)
for feature in bfill:
  data[feature].fillna(method='bfill',inplace=True)

In [ ]:
data.isna().any()

MSSubClass       False
MSZoning         False
LotFrontage      False
LotArea          False
Street           False
                 ...  
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice        False
Length: 76, dtype: bool

##Encode dataset

In [ ]:
#Find datatypes
data.dtypes

MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
                  ...   
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 76, dtype: object

In [ ]:
#filter of type object
data_categories=data.select_dtypes(include=['object']).copy()
data_categories.head(2)

MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
0       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1       RL   Pave      Reg         Lvl    AllPub       FR2       Gtl   

  Neighborhood Condition1 Condition2  ... KitchenQual Functional FireplaceQu  \
0      CollgCr       Norm       Norm  ...          Gd        Typ          TA   
1      Veenker      Feedr       Norm  ...          TA        Typ          TA   

  GarageType GarageFinish GarageQual GarageCond PavedDrive SaleType  \
0     Attchd          RFn         TA         TA          Y       WD   
1     Attchd          RFn         TA         TA          Y       WD   

  SaleCondition  
0        Normal  
1        Normal  

[2 rows x 39 columns]

In [ ]:
#list columns of type object
category_features=list(data_categories.columns)
category_features

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [ ]:
#categorize features
nominal=['MSZoning','LandContour','LotConfig','Neighborhood']
ordinal=list(set(category_features)-set(nominal))
numerical=list(set(features)-set(category_features))
target=['SalePrice']

In [ ]:
#encode data according to different types
for feature in ordinal:
  data[feature]=(data[feature].astype('category')).cat.codes
df_nominal=pd.get_dummies(data[nominal])
df_ordinal=data[ordinal]
df_numerical=data[numerical]

In [ ]:
encoded_data=pd.concat([df_numerical,df_nominal,df_ordinal],axis=1)
encoded_data

GarageYrBlt  HalfBath  SalePrice  BsmtUnfSF  MoSold  3SsnPorch  \
0          2003.0         1     208500        150       2          0   
1          1976.0         0     181500        284       5          0   
2          2001.0         1     223500        434       9          0   
3          1998.0         0     140000        540       2          0   
4          2000.0         1     250000        490      12          0   
...           ...       ...        ...        ...     ...        ...   
1455       1999.0         1     175000        953       8          0   
1456       1978.0         0     210000        589       2          0   
1457       1941.0         0     266500        877       5          0   
1458       1950.0         0     142125          0       4          0   
1459       1965.0         1     147500        136       6          0   

      YearRemodAdd  GarageCars  BsmtFinSF1  1stFlrSF  ...  Exterior2nd  \
0             2003           2         706       856  ...           13   
1             1976           2         978      1262  ...            8   
2             2002           2         486       920  ...           13   
3             1970           3         216       961  ...           15   
4             2000           3         655      1145  ...           13   
...            ...         ...         ...       ...  ...          ...   
1455          2000           2           0       953  ...           13   
1456          1988           2         790      2073  ...           10   
1457          2006           1         275      1188  ...            5   
1458          1996           1          49      1078  ...            8   
1459          1965           1         830      1256  ...            6   

      SaleType  RoofMatl  Condition1  LotShape  Condition2  HeatingQC  \
0            8         1           2         3           2          0   
1            8         1           1         3           2          0   
2            8         1           2         0           2          0   
3            8         1           2         0           2          2   
4            8         1           2         0           2          0   
...        ...       ...         ...       ...         ...        ...   
1455         8         1           2         3           2          0   
1456         8         1           2         3           2          4   
1457         8         1           2         3           2          0   
1458         8         1           2         3           2          2   
1459         8         1           2         3           2          2   

      Foundation  FireplaceQu  LandSlope  
0              2            4          0  
1              1            4          0  
2              2            4          0  
3              0            2          0  
4              2            4          0  
...          ...          ...        ...  
1455           2            4          0  
1456           1            4          0  
1457           4            2          0  
1458           1           -1          0  
1459           1           -1          0  

[1460 rows x 111 columns]

In [ ]:
encoded_data.shape

(1460, 111)

##Standardize data

In [ ]:
encoded_data.drop('SalePrice',axis=1,inplace=True)

In [ ]:
#convert to numpy array
X = encoded_data.to_numpy()
X[0]

array([2.003e+03, 1.000e+00, 1.500e+02, 2.000e+00, 0.000e+00, 2.003e+03,
       2.000e+00, 7.060e+02, 8.560e+02, 0.000e+00, 2.000e+00, 0.000e+00,
       8.540e+02, 0.000e+00, 6.100e+01, 3.000e+00, 8.560e+02, 2.008e+03,
       0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 8.000e+00,
       5.480e+02, 0.000e+00, 6.500e+01, 5.000e+00, 7.000e+00, 2.003e+03,
       0.000e+00, 1.000e+00, 1.710e+03, 6.000e+01, 8.450e+03, 1.960e+02,
       0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 2.000e+00, 1.200e+01, 2.000e+00,
       0.000e+00, 3.000e+00, 3.000e+00, 6.000e+00, 

In [ ]:
##standard scaler -> removes the mean and scales each feature/variable to unit variance
##fit_transform() -> learn the scaling parameters of that data
X=StandardScaler().fit_transform(X)
X[0]

array([ 0.98587121,  1.22758538, -0.94459061, -1.5991111 , -0.11633929,
        0.87866809,  0.31172464,  0.57542484, -0.79343379, -0.06869175,
        0.78974052, -0.3593249 ,  1.16185159, -0.75217584,  0.21650316,
        0.16377912, -0.45930254,  0.13877749, -0.08768781, -0.95122649,
       -0.28865283, -0.21145358, -0.24106104,  0.91220977,  0.35100032,
       -0.12024172, -0.22937175, -0.51719981,  0.65147924,  1.05099379,
       -0.27020835,  1.10781015,  0.37033344,  0.07337496, -0.20714171,
        0.51141841, -0.08304548, -0.21585871, -0.10526316,  0.51813339,
       -0.41895507, -0.21235968, -0.18831089, -0.15899968,  0.33712564,
       -0.46873869, -0.26232433, -0.18238027, -0.05241424,  0.62276215,
       -0.10854037, -0.03703704, -0.10526316, -0.20339487, -0.1398323 ,
        2.95522137, -0.19025216, -0.27116307, -0.23917551, -0.16124951,
       -0.10854037, -0.1863522 , -0.42683279, -0.07875671, -0.22941573,
       -0.16998114, -0.23595776, -0.28963792, -0.13199092, -0.23

In [ ]:
X.shape

(1460, 110)

In [ ]:
y=data[target]
y=y.to_numpy()
y.shape

(1460, 1)

In [ ]:
y

array([[208500],
       [181500],
       [223500],
       ...,
       [266500],
       [142125],
       [147500]])

In [ ]:
y=StandardScaler().fit_transform(y)
y

array([[ 0.34727322],
       [ 0.00728832],
       [ 0.53615372],
       ...,
       [ 1.07761115],
       [-0.48852299],
       [-0.42084081]])

##Feature extraction using PCA
#What is PCA used for?
PCA is a tool for identifying the main axes of variance within a data set and allows for easy data exploration to understand the key variables in the data and spot outliers.

In [ ]:
pca=PCA(n_components=2)

In [ ]:
p_components=pca.fit_transform(X)

In [ ]:
p_components

array([[ 2.40853566, -1.3309943 ],
       [ 0.43196247,  2.6222773 ],
       [ 2.82844417, -0.85563995],
       ...,
       [ 1.25988096, -0.86445043],
       [-2.83065906,  3.18233478],
       [-0.7566443 ,  2.68240578]])

In [ ]:
#amount of variability in a data set that can be attributed to each individual principal component
pca.explained_variance_ratio_

array([0.10207313, 0.04345606])

In [ ]:
#visualize the data
pca_data = pd.DataFrame(p_components,columns=['PC1','PC2'])
target_data = pd.DataFrame(y,columns=['SalePrice'])
final_data = pd.concat([pca_data,target_data],axis=1)
final_data

PC1       PC2  SalePrice
0     2.408536 -1.330994   0.347273
1     0.431962  2.622277   0.007288
2     2.828444 -0.855640   0.536154
3    -1.364217  0.551509  -0.515281
4     5.311986 -0.223358   0.869843
...        ...       ...        ...
1455  1.306603 -2.289688  -0.074560
1456  1.095836  3.177439   0.366161
1457  1.259881 -0.864450   1.077611
1458 -2.830659  3.182335  -0.488523
1459 -0.756644  2.682406  -0.420841

[1460 rows x 3 columns]

##Feature Selection using L1

In [ ]:
X_select = encoded_data.drop(axis=1, index=2)
y_select = encoded_data['SalePrice']
regressor=LassoCV()
regressor.fit(X_select,y_select)

KeyError: ignored